[project]
name = "adaptive-search"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]